export const USER_SUBSCRIBE = 'USER_SUBSCRIBE';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_SUBSCRIBE_NEWSLETTER = 'USER_SUBSCRIBE_NEWSLETTER';
export const SET_ADVICES = 'SET_ADVICES';
export const USER_MARK_ADVICE = 'USER_MARK_ADVICE';
export const USER_MARK_ADVICE_NEGATIVE = 'USER_MARK_ADVICE_NEGATIVE';
export const USER_MARK_ADVICE_BAD = 'USER_MARK_ADVICE_BAD';

export const UPDATE_ADVICE_INTO_COLLECTION = 'UPDATE_ADVICE_INTO_COLLECTION';

export const ACTION_ADD_USER_COLLECTION = 'ACTION_ADD_USER_COLLECTION';

export const COUNT_INSIGHTS_COLLECTIONS = 'COUNT_INSIGHTS_COLLECTIONS';
export const COUNT_INSIGHTS_PLUS = 'COUNT_INSIGHTS_PLUS';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const SET_CURRENT_COLLECTION = 'SET_CURRENT_COLLECTION';

export const TOPICS_SAVE = 'TOPICS_SAVE';
export const SET_ROOT_TOPIC = 'SET_ROOT_TOPIC';
export const TOPIC_ADD = 'TOPIC_ADD';
export const TOPIC_DELETE = 'TOPIC_DELETE';

export const SAVE_UNIQUE_ID_AND_DATE = 'SAVE_UNIQUE_ID_AND_DATE';
export const UPDATE_APP_START_TIME = 'UPDATE_APP_START_TIME';
export const APP_BACKGROUND_TIME = 'APP_BACKGROUND_TIME';

export const USER_TURN_NOTIFICATIONS = 'USER_TURN_NOTIFICATIONS';


export const SELECT_TOPIC = 'SELECT_TOPIC';
export const STORAGE_KEY = '@AsyncStorage:notification';
