export const USER_SUBSCRIBE = 'USER_SUBSCRIBE';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_SUBSCRIBE_NEWSLETTER = 'USER_SUBSCRIBE_NEWSLETTER';
export const SET_ADVICES = 'SET_ADVICES';

export const ACTION_ADD_USER_COLLECTION = 'ACTION_ADD_USER_COLLECTION';

export const COUNT_INSIGHTS_COLLECTIONS = 'COUNT_INSIGHTS_COLLECTIONS';
export const COUNT_INSIGHTS_PLUS = 'COUNT_INSIGHTS_PLUS';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const SET_CURRENT_COLLECTION = 'SET_CURRENT_COLLECTION';
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';

export const TOPICS_SAVE = 'TOPICS_SAVE';
export const SET_ROOT_TOPIC = 'SET_ROOT_TOPIC';
export const TOPIC_ADD = 'TOPIC_ADD';
export const TOPIC_DELETE = 'TOPIC_DELETE';

export const SAVE_UNIQUE_ID_AND_DATE = 'SAVE_UNIQUE_ID_AND_DATE';
export const USER_TURN_NOTIFICATIONS = 'USER_TURN_NOTIFICATIONS';


export const UPDATE_APP_START_TIME = '@AsyncStorage:UPDATE_APP_START_TIME';
export const APP_BACKGROUND_TIME = '@AsyncStorage:APP_BACKGROUND_TIME';
export const STORAGE_KEY = '@AsyncStorage:notification';


export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
