export const USER_SUBSCRIBE = 'USER_SUBSCRIBE';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_SUBSCRIBE_NEWSLETTER = 'USER_SUBSCRIBE_NEWSLETTER';
export const USER_MARK_ADVICE = 'USER_MARK_ADVICE';
export const USER_MARK_ADVICE_NEGATIVE = 'USER_MARK_ADVICE_NEGATIVE';
export const USER_MARK_ADVICE_BAD = 'USER_MARK_ADVICE_BAD';

export const UPDATE_ADVICE_INTO_COLLECTION = 'UPDATE_ADVICE_INTO_COLLECTION';

export const ACTION_ADD_USER_COLLECTION = 'ACTION_ADD_USER_COLLECTION';

export const CREATE_COLLECTIONS = 'CREATE_COLLECTIONS';
export const ADD_TO_COLLECTIONS = 'ADD_TO_COLLECTIONS';
export const DELETE_COLLECTIONS = 'DELETE_COLLECTIONS';
export const DELETE_FROM_COLLECTIONS = 'DELETE_FROM_COLLECTIONS';

export const WATCH_COLLECTION = 'DELETE_FROM_COLLECTIONS';

export const TOPIC_ADD = 'TOPIC_ADD';
export const TOPIC_DELETE = 'TOPIC_DELETE';

export const SAVE_UNIQUE_ID_AND_DATE = 'SAVE_UNIQUE_ID_AND_DATE';
export const UPDATE_APP_START_TIME = 'UPDATE_APP_START_TIME';
export const APP_BACKGROUND_TIME = 'APP_BACKGROUND_TIME';

export const USER_TURN_NOTIFICATIONS = 'USER_TURN_NOTIFICATIONS';

export const SELECT_TOPIC = 'SELECT_TOPIC';
