export const APPLICATION__IS_FIRST_LAUNCH = 'APPLICATION__IS_FIRST_LAUNCH'
export const APPLICATION__START_TIME = 'APPLICATION__START_TIME'
export const APPLICATION__BACKGROUND_TIME = 'APPLICATION__BACKGROUND_TIME'
export const NOTIFICATIONS__PERMISSIONS_STATUS = 'NOTIFICATIONS__PERMISSIONS_STATUS'
